version: '3.8'

services:
  api:
    build: .
    container_name: golearn-api
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - JWT_SECRET=super-secret-key
    volumes:
      - golearn_data:/root/

volumes:
  golearn_data:
